= Proyecto Primer Parcial
Alejandro Bermudez Cardenas <abc65717@udelasalle.edu.mx>
:doctype: book
:toc: 
:imagesdir: Images
:sectnums: 
:toclevels: 3
:chapter-label: Section

== Project description

No description found (add content in project description)

== Code component descriptions

=== DQMH(R) modules

This section describes DQMH(R) module responsibilities and relationships.

==== Preamble

A DQMH module is the main component of an architecture based on DQMH(R) framework. A DQMH module is used to implement a section of the application that has one responsibility.

DQMH(R) framework defines two different type of DQMH module.  

====
*Singleton:*

A Singleton DQMH module can have only one instance running at any given time.
====

====
*Cloneable:*

A Cloneable DQMH module can have one or multiple instances running in parallel.
====

DQMH(R) framework defines two different ways to carry data throughout the application and with both other DQMH modules and non-DQMH based code.

====
*Request events:*

A request is a code that fires an event requesting the DQMH module to do something. Multiple locations in the code can send events to the DQMH module.

Request events are many-to-one.

Requests are usually named using imperative tense.
====

====
*Broadcast events:*

A broadcast is a code that fires an event broadcasting that the DQMH module did something. Multiple Event Structures can register to handle the Broadcast Events.

Broadcast Events are one-to-many.

Broadcasts are usually named using past tense or passive voice.
====

NOTE: Refer to the DQMH(R) framework official http://delacor.com/documentation/dqmh-html/[documentation] to find more details on how the framework works


The following section gives you details on the project architecture relying on this framework.
It gives you an overview of the modules' interaction and detailed information on each module.

Graphs used in this section have the following legend:

*Components:*


[graphviz, format="png", align="center"]
....
digraph G93120 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"DQMH module / Lvlib"[color=black shape=component]
"Vi"[color=skyblue shape=note]
}
....

*Events:*

[graphviz, format="png", align="center"]
....
digraph G667856 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
" "[color=white shape=box]
"  "[color=white shape=box]
"   "[color=white shape=box]
"    "[color=white shape=box]
" " -> "  " [label="Request to a DQMH module" dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"   " -> "    " [label="Broadcast from a DQMH module" dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
}
....

*Start and Stop module callers:*

[graphviz, format="png", align="center"]
....
digraph G9510051 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Start Module
caller"[color=black shape=component]
"Start Module"[color=yellowgreen shape=note]
"Start Module" -> "Start Module
caller" [label="Called by" dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
}
....

[graphviz, format="png", align="center"]
....
digraph G456990 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Stop Module
caller"[color=black shape=component]
"Stop Module"[color=tomato shape=note]
"Stop Module" -> "Stop Module
caller" [label="Called by" dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
}
....


==== Modules overview

This project contains the following modules.

.Modules list
|===
|Singleton|Cloneable

|<<Adquisicion.lvlib>>
|

|<<Analisis.lvlib>>
|

|<<Base de datos.lvlib>>
|

|<<Config.lvlib>>
|

|<<Mensajes.lvlib>>
|

|<<UI.lvlib>>
|
|===

This graph represents the links between all DQMH modules.

[graphviz, format="png", align="center"]
....
digraph G553474 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"UI"[color=black shape=component]
"Adquisicion"[color=black shape=component]
"Config"[color=black shape=component]
"Analisis"[color=black shape=component]
"Base de datos"[color=black shape=component]
"Mensajes"[color=black shape=component]
"Adquisicion" -> "Adquisicion" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"UI" -> "Adquisicion" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Config" -> "Adquisicion" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Analisis" -> "Analisis" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"UI" -> "Analisis" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Base de datos" -> "Base de datos" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"UI" -> "Base de datos" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Analisis" -> "Base de datos" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"UI" -> "Config" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Config" -> "Config" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Mensajes" -> "Mensajes" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"UI" -> "Mensajes" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"UI" -> "UI" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
}
....


==== Adquisicion.lvlib

*Type:* Singleton

*Responsibility*: No description found (add content in DQMH module lvlib description)

===== Module Start/Stop calls

[graphviz, format="png", align="center"]
....
digraph G384526 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Start Module"[color=yellowgreen shape=note]
"UI"[color=black shape=component]
"Test Adquisicion API"[color=skyblue shape=note]
"Stop Module"[color=tomato shape=note]
"Adquisicion"[color=black shape=component]
"Start Module" -> "UI" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Start Module" -> "Test Adquisicion API" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Stop Module" -> "UI" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "Adquisicion" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "Test Adquisicion API" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
}
....

.Start and Stop module callers
|===
|Function|Callers

|<<Adquisicion.lvlib:Start Module.vi>>
|UI.lvlib:Main.vi +
Test Adquisicion API.vi

|<<Adquisicion.lvlib:Stop Module.vi>>
|UI.lvlib:Main.vi +
Adquisicion.lvlib:Handle Exit.vi +
Test Adquisicion API.vi
|===

===== Module relationship

[graphviz, format="png", align="center"]
....
digraph G509280 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Adquisicion"[color=slateblue shape=component]
"UI"[color=black shape=component]
"Test Adquisicion API"[color=skyblue shape=note]
"Config"[color=black shape=component]
"UI" -> "Adquisicion" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Test Adquisicion API" -> "Adquisicion" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Adquisicion" -> "Adquisicion" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Config" -> "Adquisicion" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Adquisicion" -> "Test Adquisicion API" [label=" " dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
"Adquisicion" -> "Adquisicion" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
}
....

.Requests callers
|===
|Request Name|Callers

|<<Adquisicion.lvlib:Show Panel.vi>>
|Test Adquisicion API.vi

|<<Adquisicion.lvlib:Hide Panel.vi>>
|Test Adquisicion API.vi

|<<Adquisicion.lvlib:Get Module Execution Status.vi>>
|Adquisicion.lvlib:Start Module.vi +
Adquisicion.lvlib:Obtain Broadcast Events for Registration.vi

|<<Adquisicion.lvlib:Show Diagram.vi>>
|Test Adquisicion API.vi

|<<Adquisicion.lvlib:Iniciar adquisicion.vi>>
|UI.lvlib:Main.vi +
Test Adquisicion API.vi

|<<Adquisicion.lvlib:Parar adquisicion.vi>>
|UI.lvlib:Main.vi +
Test Adquisicion API.vi

|<<Adquisicion.lvlib:Config adquisicion.vi>>
|Config.lvlib:Main.vi +
Test Adquisicion API.vi
|===

.Broadcasts Listeners
|===
|Broadcast Name|Listeners

|<<Adquisicion.lvlib:Module Did Init.vi>>
|Test Adquisicion API.vi

|<<Adquisicion.lvlib:Status Updated.vi>>
|Test Adquisicion API.vi

|<<Adquisicion.lvlib:Error Reported.vi>>
|Test Adquisicion API.vi

|<<Adquisicion.lvlib:Module Did Stop.vi>>
|Test Adquisicion API.vi

|<<Adquisicion.lvlib:Update Module Execution Status.vi>>
|Test Adquisicion API.vi
|===

.Used requests
|===
|Module|Brodcasts

|<<Adquisicion.lvlib>>
|Adquisicion.lvlib:Get Module Execution Status.vi
|===

.Registred broadcast
|===
|Module|Brodcasts

|--
|--
|===

==== Analisis.lvlib

*Type:* Singleton

*Responsibility*: No description found (add content in DQMH module lvlib description)

===== Module Start/Stop calls

[graphviz, format="png", align="center"]
....
digraph G765816 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Start Module"[color=yellowgreen shape=note]
"UI"[color=black shape=component]
"Test Analisis API"[color=skyblue shape=note]
"Stop Module"[color=tomato shape=note]
"Analisis"[color=black shape=component]
"Start Module" -> "UI" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Start Module" -> "Test Analisis API" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Stop Module" -> "UI" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "Analisis" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "Test Analisis API" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
}
....

.Start and Stop module callers
|===
|Function|Callers

|<<Analisis.lvlib:Start Module.vi>>
|UI.lvlib:Main.vi +
Test Analisis API.vi

|<<Analisis.lvlib:Stop Module.vi>>
|UI.lvlib:Main.vi +
Analisis.lvlib:Handle Exit.vi +
Test Analisis API.vi
|===

===== Module relationship

[graphviz, format="png", align="center"]
....
digraph G181799 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Analisis"[color=slateblue shape=component]
"UI"[color=black shape=component]
"Test Analisis API"[color=skyblue shape=note]
"Base de datos"[color=black shape=component]
"UI" -> "Analisis" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Test Analisis API" -> "Analisis" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Analisis" -> "Analisis" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Analisis" -> "Test Analisis API" [label=" " dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
"Analisis" -> "Analisis" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
"Analisis" -> "Base de datos" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
}
....

.Requests callers
|===
|Request Name|Callers

|<<Analisis.lvlib:Show Panel.vi>>
|Test Analisis API.vi

|<<Analisis.lvlib:Hide Panel.vi>>
|Test Analisis API.vi

|<<Analisis.lvlib:Get Module Execution Status.vi>>
|Analisis.lvlib:Start Module.vi +
Analisis.lvlib:Obtain Broadcast Events for Registration.vi

|<<Analisis.lvlib:Show Diagram.vi>>
|Test Analisis API.vi

|<<Analisis.lvlib:Iniciar analisis.vi>>
|UI.lvlib:Main.vi +
Test Analisis API.vi

|<<Analisis.lvlib:Parar Analisis.vi>>
|UI.lvlib:Main.vi +
Test Analisis API.vi

|<<Analisis.lvlib:Analisis de imagenes.vi>>
|Test Analisis API.vi
|===

.Broadcasts Listeners
|===
|Broadcast Name|Listeners

|<<Analisis.lvlib:Module Did Init.vi>>
|Test Analisis API.vi

|<<Analisis.lvlib:Status Updated.vi>>
|Test Analisis API.vi

|<<Analisis.lvlib:Error Reported.vi>>
|Test Analisis API.vi

|<<Analisis.lvlib:Module Did Stop.vi>>
|Test Analisis API.vi

|<<Analisis.lvlib:Update Module Execution Status.vi>>
|Test Analisis API.vi
|===

.Used requests
|===
|Module|Brodcasts

|<<Analisis.lvlib>>
|Analisis.lvlib:Get Module Execution Status.vi

|<<Base de datos.lvlib>>
|Base de datos.lvlib:Datos de analisis.vi
|===

.Registred broadcast
|===
|Module|Brodcasts

|--
|--
|===

==== Base de datos.lvlib

*Type:* Singleton

*Responsibility*: No description found (add content in DQMH module lvlib description)

===== Module Start/Stop calls

[graphviz, format="png", align="center"]
....
digraph G261166 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Start Module"[color=yellowgreen shape=note]
"UI"[color=black shape=component]
"Test Base de datos API"[color=skyblue shape=note]
"Stop Module"[color=tomato shape=note]
"Base de datos"[color=black shape=component]
"Start Module" -> "UI" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Start Module" -> "Test Base de datos API" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Stop Module" -> "UI" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "Base de datos" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "Test Base de datos API" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
}
....

.Start and Stop module callers
|===
|Function|Callers

|<<Base de datos.lvlib:Start Module.vi>>
|UI.lvlib:Main.vi +
Test Base de datos API.vi

|<<Base de datos.lvlib:Stop Module.vi>>
|UI.lvlib:Main.vi +
Base de datos.lvlib:Handle Exit.vi +
Test Base de datos API.vi
|===

===== Module relationship

[graphviz, format="png", align="center"]
....
digraph G928185 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Base de datos"[color=slateblue shape=component]
"UI"[color=black shape=component]
"Test Base de datos API"[color=skyblue shape=note]
"Analisis"[color=black shape=component]
"UI" -> "Base de datos" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Test Base de datos API" -> "Base de datos" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Base de datos" -> "Base de datos" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Analisis" -> "Base de datos" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Base de datos" -> "Test Base de datos API" [label=" " dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
"Base de datos" -> "Base de datos" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
}
....

.Requests callers
|===
|Request Name|Callers

|<<Base de datos.lvlib:Show Panel.vi>>
|Test Base de datos API.vi

|<<Base de datos.lvlib:Hide Panel.vi>>
|Test Base de datos API.vi

|<<Base de datos.lvlib:Get Module Execution Status.vi>>
|Base de datos.lvlib:Start Module.vi +
Base de datos.lvlib:Obtain Broadcast Events for Registration.vi

|<<Base de datos.lvlib:Show Diagram.vi>>
|Test Base de datos API.vi

|<<Base de datos.lvlib:Config Database.vi>>
|Test Base de datos API.vi

|<<Base de datos.lvlib:Iniciar base de datos.vi>>
|UI.lvlib:Main.vi +
Test Base de datos API.vi

|<<Base de datos.lvlib:Parar Base de datos.vi>>
|UI.lvlib:Main.vi +
Test Base de datos API.vi

|<<Base de datos.lvlib:Escribir.vi>>
|Test Base de datos API.vi

|<<Base de datos.lvlib:Datos de analisis.vi>>
|Analisis.lvlib:Main.vi +
Test Base de datos API.vi
|===

.Broadcasts Listeners
|===
|Broadcast Name|Listeners

|<<Base de datos.lvlib:Module Did Init.vi>>
|Test Base de datos API.vi

|<<Base de datos.lvlib:Status Updated.vi>>
|Test Base de datos API.vi

|<<Base de datos.lvlib:Error Reported.vi>>
|Test Base de datos API.vi

|<<Base de datos.lvlib:Module Did Stop.vi>>
|Test Base de datos API.vi

|<<Base de datos.lvlib:Update Module Execution Status.vi>>
|Test Base de datos API.vi
|===

.Used requests
|===
|Module|Brodcasts

|<<Base de datos.lvlib>>
|Base de datos.lvlib:Get Module Execution Status.vi
|===

.Registred broadcast
|===
|Module|Brodcasts

|--
|--
|===

==== Config.lvlib

*Type:* Singleton

*Responsibility*: No description found (add content in DQMH module lvlib description)

===== Module Start/Stop calls

[graphviz, format="png", align="center"]
....
digraph G492497 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Start Module"[color=yellowgreen shape=note]
"UI"[color=black shape=component]
"Test Config API"[color=skyblue shape=note]
"Stop Module"[color=tomato shape=note]
"Config"[color=black shape=component]
"Start Module" -> "UI" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Start Module" -> "Test Config API" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Stop Module" -> "Config" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "Test Config API" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
}
....

.Start and Stop module callers
|===
|Function|Callers

|<<Config.lvlib:Start Module.vi>>
|UI.lvlib:Main.vi +
Test Config API.vi

|<<Config.lvlib:Stop Module.vi>>
|Config.lvlib:Handle Exit.vi +
Test Config API.vi
|===

===== Module relationship

[graphviz, format="png", align="center"]
....
digraph G376639 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Config"[color=slateblue shape=component]
"UI"[color=black shape=component]
"Test Config API"[color=skyblue shape=note]
"Adquisicion"[color=black shape=component]
"UI" -> "Config" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Test Config API" -> "Config" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Config" -> "Config" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Config" -> "Test Config API" [label=" " dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
"Config" -> "Adquisicion" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
"Config" -> "Config" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
}
....

.Requests callers
|===
|Request Name|Callers

|<<Config.lvlib:Show Panel.vi>>
|UI.lvlib:Main.vi +
Test Config API.vi

|<<Config.lvlib:Hide Panel.vi>>
|Test Config API.vi

|<<Config.lvlib:Get Module Execution Status.vi>>
|Config.lvlib:Start Module.vi +
Config.lvlib:Obtain Broadcast Events for Registration.vi

|<<Config.lvlib:Show Diagram.vi>>
|Test Config API.vi
|===

.Broadcasts Listeners
|===
|Broadcast Name|Listeners

|<<Config.lvlib:Module Did Init.vi>>
|Test Config API.vi

|<<Config.lvlib:Status Updated.vi>>
|Test Config API.vi

|<<Config.lvlib:Error Reported.vi>>
|Test Config API.vi

|<<Config.lvlib:Module Did Stop.vi>>
|Test Config API.vi

|<<Config.lvlib:Update Module Execution Status.vi>>
|Test Config API.vi
|===

.Used requests
|===
|Module|Brodcasts

|<<Adquisicion.lvlib>>
|Adquisicion.lvlib:Config adquisicion.vi

|<<Config.lvlib>>
|Config.lvlib:Get Module Execution Status.vi
|===

.Registred broadcast
|===
|Module|Brodcasts

|--
|--
|===

==== Mensajes.lvlib

*Type:* Singleton

*Responsibility*: No description found (add content in DQMH module lvlib description)

===== Module Start/Stop calls

[graphviz, format="png", align="center"]
....
digraph G4988 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Start Module"[color=yellowgreen shape=note]
"UI"[color=black shape=component]
"Test Mensajes API"[color=skyblue shape=note]
"Stop Module"[color=tomato shape=note]
"Mensajes"[color=black shape=component]
"Start Module" -> "UI" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Start Module" -> "Test Mensajes API" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Stop Module" -> "UI" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "Mensajes" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "Test Mensajes API" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
}
....

.Start and Stop module callers
|===
|Function|Callers

|<<Mensajes.lvlib:Start Module.vi>>
|UI.lvlib:Main.vi +
Test Mensajes API.vi

|<<Mensajes.lvlib:Stop Module.vi>>
|UI.lvlib:Main.vi +
Mensajes.lvlib:Handle Exit.vi +
Test Mensajes API.vi
|===

===== Module relationship

[graphviz, format="png", align="center"]
....
digraph G494397 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Mensajes"[color=slateblue shape=component]
"UI"[color=black shape=component]
"Test Mensajes API"[color=skyblue shape=note]
"UI" -> "Mensajes" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Test Mensajes API" -> "Mensajes" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Mensajes" -> "Mensajes" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Mensajes" -> "Test Mensajes API" [label=" " dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
"Mensajes" -> "Mensajes" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
}
....

.Requests callers
|===
|Request Name|Callers

|<<Mensajes.lvlib:Show Panel.vi>>
|Test Mensajes API.vi

|<<Mensajes.lvlib:Hide Panel.vi>>
|Test Mensajes API.vi

|<<Mensajes.lvlib:Get Module Execution Status.vi>>
|Mensajes.lvlib:Start Module.vi +
Mensajes.lvlib:Obtain Broadcast Events for Registration.vi

|<<Mensajes.lvlib:Show Diagram.vi>>
|Test Mensajes API.vi

|<<Mensajes.lvlib:Mandar mensajes.vi>>
|UI.lvlib:Main.vi +
Test Mensajes API.vi
|===

.Broadcasts Listeners
|===
|Broadcast Name|Listeners

|<<Mensajes.lvlib:Module Did Init.vi>>
|Test Mensajes API.vi

|<<Mensajes.lvlib:Status Updated.vi>>
|Test Mensajes API.vi

|<<Mensajes.lvlib:Error Reported.vi>>
|Test Mensajes API.vi

|<<Mensajes.lvlib:Module Did Stop.vi>>
|Test Mensajes API.vi

|<<Mensajes.lvlib:Update Module Execution Status.vi>>
|Test Mensajes API.vi
|===

.Used requests
|===
|Module|Brodcasts

|<<Mensajes.lvlib>>
|Mensajes.lvlib:Get Module Execution Status.vi
|===

.Registred broadcast
|===
|Module|Brodcasts

|--
|--
|===

==== UI.lvlib

*Type:* Singleton

*Responsibility*: No description found (add content in DQMH module lvlib description)

===== Module Start/Stop calls

[graphviz, format="png", align="center"]
....
digraph G142424 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Start Module"[color=yellowgreen shape=note]
"Test UI API"[color=skyblue shape=note]
"Stop Module"[color=tomato shape=note]
"UI"[color=black shape=component]
"Start Module" -> "Test UI API" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Stop Module" -> "UI" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "Test UI API" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
}
....

.Start and Stop module callers
|===
|Function|Callers

|<<UI.lvlib:Start Module.vi>>
|Test UI API.vi

|<<UI.lvlib:Stop Module.vi>>
|UI.lvlib:Handle Exit.vi +
Test UI API.vi
|===

===== Module relationship

[graphviz, format="png", align="center"]
....
digraph G808267 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"UI"[color=slateblue shape=component]
"Test UI API"[color=skyblue shape=note]
"Adquisicion"[color=black shape=component]
"Analisis"[color=black shape=component]
"Base de datos"[color=black shape=component]
"Config"[color=black shape=component]
"Mensajes"[color=black shape=component]
"Test UI API" -> "UI" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"UI" -> "UI" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"UI" -> "Test UI API" [label=" " dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
"UI" -> "Adquisicion" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
"UI" -> "Analisis" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
"UI" -> "Base de datos" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
"UI" -> "Config" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
"UI" -> "Mensajes" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
"UI" -> "UI" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
}
....

.Requests callers
|===
|Request Name|Callers

|<<UI.lvlib:Show Panel.vi>>
|Test UI API.vi

|<<UI.lvlib:Hide Panel.vi>>
|Test UI API.vi

|<<UI.lvlib:Get Module Execution Status.vi>>
|UI.lvlib:Start Module.vi +
UI.lvlib:Obtain Broadcast Events for Registration.vi

|<<UI.lvlib:Show Diagram.vi>>
|Test UI API.vi
|===

.Broadcasts Listeners
|===
|Broadcast Name|Listeners

|<<UI.lvlib:Module Did Init.vi>>
|Test UI API.vi

|<<UI.lvlib:Status Updated.vi>>
|Test UI API.vi

|<<UI.lvlib:Error Reported.vi>>
|Test UI API.vi

|<<UI.lvlib:Module Did Stop.vi>>
|Test UI API.vi

|<<UI.lvlib:Update Module Execution Status.vi>>
|Test UI API.vi
|===

.Used requests
|===
|Module|Brodcasts

|<<Adquisicion.lvlib>>
|Adquisicion.lvlib:Iniciar adquisicion.vi +
Adquisicion.lvlib:Parar adquisicion.vi

|<<Analisis.lvlib>>
|Analisis.lvlib:Iniciar analisis.vi +
Analisis.lvlib:Parar Analisis.vi

|<<Base de datos.lvlib>>
|Base de datos.lvlib:Iniciar base de datos.vi +
Base de datos.lvlib:Parar Base de datos.vi

|<<Config.lvlib>>
|Config.lvlib:Show Panel.vi

|<<Mensajes.lvlib>>
|Mensajes.lvlib:Mandar mensajes.vi

|<<UI.lvlib>>
|UI.lvlib:Get Module Execution Status.vi
|===

.Registred broadcast
|===
|Module|Brodcasts

|--
|--
|===

=== Libraries

This section describes the libraries contained in the project.

=== Classes

This section describes the classes contained in the project.

== VI descriptions

=== DQMH(R) modules

This section describes DQMH(R) modules events.

==== Adquisicion.lvlib

===== Adquisicion.lvlib:Start Module.vi

*Event type:* Not a DQMH Event

:imgpath: Adquisicion.lvlib_Start Module.vi.png
image::{imgpath}[Adquisicion.lvlib:Start Module.vi]

*Description:*
++++
Launches the Module Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Adquisicion.lvlib:Stop Module.vi

*Event type:* Not a DQMH Event

:imgpath: Adquisicion.lvlib_Stop Module.vi.png
image::{imgpath}[Adquisicion.lvlib:Stop Module.vi]

*Description:*
++++
Send the Stop request to the Module's Main.vi.

If <b>Wait for Module to Stop?</b> is TRUE, this VI will wait until the module main VI stops, and will timeout at the <b>Timeout to Wait for Stop</b> value. This value defaults to "-1", which means the VI will not timeout, and will always wait until the module main VI stops before completing execution.

Note: The <b>Timeout to Wait for Stop</b> value is ignored if 'Wait for Module to Stop?' is set to FALSE.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Adquisicion.lvlib:Show Panel.vi

*Event type:* Request

:imgpath: Adquisicion.lvlib_Show Panel.vi.png
image::{imgpath}[Adquisicion.lvlib:Show Panel.vi]

*Description:*
++++
Send the Show Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Adquisicion.lvlib:Hide Panel.vi

*Event type:* Request

:imgpath: Adquisicion.lvlib_Hide Panel.vi.png
image::{imgpath}[Adquisicion.lvlib:Hide Panel.vi]

*Description:*
++++
Send the Hide Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Adquisicion.lvlib:Get Module Execution Status.vi

*Event type:* Request

:imgpath: Adquisicion.lvlib_Get Module Execution Status.vi.png
image::{imgpath}[Adquisicion.lvlib:Get Module Execution Status.vi]

*Description:*
++++
Fire the Get Module Execution Status request.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Adquisicion.lvlib:Show Diagram.vi

*Event type:* Request

:imgpath: Adquisicion.lvlib_Show Diagram.vi.png
image::{imgpath}[Adquisicion.lvlib:Show Diagram.vi]

*Description:*
++++
This VI tells the Module to show its block diagram to facilitate troubleshooting (add probes, breakpoints, highlight execution, etc).

_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Adquisicion.lvlib:Iniciar adquisicion.vi

*Event type:* Request

:imgpath: Adquisicion.lvlib_Iniciar adquisicion.vi.png
image::{imgpath}[Adquisicion.lvlib:Iniciar adquisicion.vi]

*Description:*
++++
Iniciar adquisicion
_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Adquisicion.lvlib:Parar adquisicion.vi

*Event type:* Request

:imgpath: Adquisicion.lvlib_Parar adquisicion.vi.png
image::{imgpath}[Adquisicion.lvlib:Parar adquisicion.vi]

*Description:*
++++

_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Adquisicion.lvlib:Config adquisicion.vi

*Event type:* Request

:imgpath: Adquisicion.lvlib_Config adquisicion.vi.png
image::{imgpath}[Adquisicion.lvlib:Config adquisicion.vi]

*Description:*
++++
Entra la configuracion de adquicision
_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Adquisicion.lvlib:Module Did Init.vi

*Event type:* Broadcast

:imgpath: Adquisicion.lvlib_Module Did Init.vi.png
image::{imgpath}[Adquisicion.lvlib:Module Did Init.vi]

*Description:*
++++
Send the Module Did Init event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Adquisicion.lvlib:Status Updated.vi

*Event type:* Broadcast

:imgpath: Adquisicion.lvlib_Status Updated.vi.png
image::{imgpath}[Adquisicion.lvlib:Status Updated.vi]

*Description:*
++++
Send the Status Updated event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Adquisicion.lvlib:Error Reported.vi

*Event type:* Broadcast

:imgpath: Adquisicion.lvlib_Error Reported.vi.png
image::{imgpath}[Adquisicion.lvlib:Error Reported.vi]

*Description:*
++++
Send the Error Reported event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Adquisicion.lvlib:Module Did Stop.vi

*Event type:* Broadcast

:imgpath: Adquisicion.lvlib_Module Did Stop.vi.png
image::{imgpath}[Adquisicion.lvlib:Module Did Stop.vi]

*Description:*
++++
Send the Module Did Stop event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Adquisicion.lvlib:Update Module Execution Status.vi

*Event type:* Broadcast

:imgpath: Adquisicion.lvlib_Update Module Execution Status.vi.png
image::{imgpath}[Adquisicion.lvlib:Update Module Execution Status.vi]

*Description:*
++++
Broadcast event to specify whether or not the module is running.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

==== Analisis.lvlib

===== Analisis.lvlib:Start Module.vi

*Event type:* Not a DQMH Event

:imgpath: Analisis.lvlib_Start Module.vi.png
image::{imgpath}[Analisis.lvlib:Start Module.vi]

*Description:*
++++
Launches the Module Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Analisis.lvlib:Stop Module.vi

*Event type:* Not a DQMH Event

:imgpath: Analisis.lvlib_Stop Module.vi.png
image::{imgpath}[Analisis.lvlib:Stop Module.vi]

*Description:*
++++
Send the Stop request to the Module's Main.vi.

If <b>Wait for Module to Stop?</b> is TRUE, this VI will wait until the module main VI stops, and will timeout at the <b>Timeout to Wait for Stop</b> value. This value defaults to "-1", which means the VI will not timeout, and will always wait until the module main VI stops before completing execution.

Note: The <b>Timeout to Wait for Stop</b> value is ignored if 'Wait for Module to Stop?' is set to FALSE.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Analisis.lvlib:Show Panel.vi

*Event type:* Request

:imgpath: Analisis.lvlib_Show Panel.vi.png
image::{imgpath}[Analisis.lvlib:Show Panel.vi]

*Description:*
++++
Send the Show Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Analisis.lvlib:Hide Panel.vi

*Event type:* Request

:imgpath: Analisis.lvlib_Hide Panel.vi.png
image::{imgpath}[Analisis.lvlib:Hide Panel.vi]

*Description:*
++++
Send the Hide Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Analisis.lvlib:Get Module Execution Status.vi

*Event type:* Request

:imgpath: Analisis.lvlib_Get Module Execution Status.vi.png
image::{imgpath}[Analisis.lvlib:Get Module Execution Status.vi]

*Description:*
++++
Fire the Get Module Execution Status request.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Analisis.lvlib:Show Diagram.vi

*Event type:* Request

:imgpath: Analisis.lvlib_Show Diagram.vi.png
image::{imgpath}[Analisis.lvlib:Show Diagram.vi]

*Description:*
++++
This VI tells the Module to show its block diagram to facilitate troubleshooting (add probes, breakpoints, highlight execution, etc).

_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Analisis.lvlib:Iniciar analisis.vi

*Event type:* Request

:imgpath: Analisis.lvlib_Iniciar analisis.vi.png
image::{imgpath}[Analisis.lvlib:Iniciar analisis.vi]

*Description:*
++++
Se inicia el proceso de analisis 
_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Analisis.lvlib:Parar Analisis.vi

*Event type:* Request

:imgpath: Analisis.lvlib_Parar Analisis.vi.png
image::{imgpath}[Analisis.lvlib:Parar Analisis.vi]

*Description:*
++++
Se detiene el analisis de imagenes
_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Analisis.lvlib:Analisis de imagenes.vi

*Event type:* Request

:imgpath: Analisis.lvlib_Analisis de imagenes.vi.png
image::{imgpath}[Analisis.lvlib:Analisis de imagenes.vi]

*Description:*
++++
Se obtiene la imagen a analisar de la parte de adquicion
_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Analisis.lvlib:Module Did Init.vi

*Event type:* Broadcast

:imgpath: Analisis.lvlib_Module Did Init.vi.png
image::{imgpath}[Analisis.lvlib:Module Did Init.vi]

*Description:*
++++
Send the Module Did Init event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Analisis.lvlib:Status Updated.vi

*Event type:* Broadcast

:imgpath: Analisis.lvlib_Status Updated.vi.png
image::{imgpath}[Analisis.lvlib:Status Updated.vi]

*Description:*
++++
Send the Status Updated event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Analisis.lvlib:Error Reported.vi

*Event type:* Broadcast

:imgpath: Analisis.lvlib_Error Reported.vi.png
image::{imgpath}[Analisis.lvlib:Error Reported.vi]

*Description:*
++++
Send the Error Reported event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Analisis.lvlib:Module Did Stop.vi

*Event type:* Broadcast

:imgpath: Analisis.lvlib_Module Did Stop.vi.png
image::{imgpath}[Analisis.lvlib:Module Did Stop.vi]

*Description:*
++++
Send the Module Did Stop event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Analisis.lvlib:Update Module Execution Status.vi

*Event type:* Broadcast

:imgpath: Analisis.lvlib_Update Module Execution Status.vi.png
image::{imgpath}[Analisis.lvlib:Update Module Execution Status.vi]

*Description:*
++++
Broadcast event to specify whether or not the module is running.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

==== Base de datos.lvlib

===== Base de datos.lvlib:Start Module.vi

*Event type:* Not a DQMH Event

:imgpath: Base de datos.lvlib_Start Module.vi.png
image::{imgpath}[Base de datos.lvlib:Start Module.vi]

*Description:*
++++
Launches the Module Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Base de datos.lvlib:Stop Module.vi

*Event type:* Not a DQMH Event

:imgpath: Base de datos.lvlib_Stop Module.vi.png
image::{imgpath}[Base de datos.lvlib:Stop Module.vi]

*Description:*
++++
Send the Stop request to the Module's Main.vi.

If <b>Wait for Module to Stop?</b> is TRUE, this VI will wait until the module main VI stops, and will timeout at the <b>Timeout to Wait for Stop</b> value. This value defaults to "-1", which means the VI will not timeout, and will always wait until the module main VI stops before completing execution.

Note: The <b>Timeout to Wait for Stop</b> value is ignored if 'Wait for Module to Stop?' is set to FALSE.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Base de datos.lvlib:Show Panel.vi

*Event type:* Request

:imgpath: Base de datos.lvlib_Show Panel.vi.png
image::{imgpath}[Base de datos.lvlib:Show Panel.vi]

*Description:*
++++
Send the Show Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Base de datos.lvlib:Hide Panel.vi

*Event type:* Request

:imgpath: Base de datos.lvlib_Hide Panel.vi.png
image::{imgpath}[Base de datos.lvlib:Hide Panel.vi]

*Description:*
++++
Send the Hide Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Base de datos.lvlib:Get Module Execution Status.vi

*Event type:* Request

:imgpath: Base de datos.lvlib_Get Module Execution Status.vi.png
image::{imgpath}[Base de datos.lvlib:Get Module Execution Status.vi]

*Description:*
++++
Fire the Get Module Execution Status request.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Base de datos.lvlib:Show Diagram.vi

*Event type:* Request

:imgpath: Base de datos.lvlib_Show Diagram.vi.png
image::{imgpath}[Base de datos.lvlib:Show Diagram.vi]

*Description:*
++++
This VI tells the Module to show its block diagram to facilitate troubleshooting (add probes, breakpoints, highlight execution, etc).

_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Base de datos.lvlib:Config Database.vi

*Event type:* Request

:imgpath: Base de datos.lvlib_Config Database.vi.png
image::{imgpath}[Base de datos.lvlib:Config Database.vi]

*Description:*
++++
Se configura la base de datos
_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Base de datos.lvlib:Iniciar base de datos.vi

*Event type:* Request

:imgpath: Base de datos.lvlib_Iniciar base de datos.vi.png
image::{imgpath}[Base de datos.lvlib:Iniciar base de datos.vi]

*Description:*
++++
Se inicia el guardado en la base de datos
_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Base de datos.lvlib:Parar Base de datos.vi

*Event type:* Request

:imgpath: Base de datos.lvlib_Parar Base de datos.vi.png
image::{imgpath}[Base de datos.lvlib:Parar Base de datos.vi]

*Description:*
++++
Se detiene el guardado en la base de datos

_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Base de datos.lvlib:Escribir.vi

*Event type:* Request

:imgpath: Base de datos.lvlib_Escribir.vi.png
image::{imgpath}[Base de datos.lvlib:Escribir.vi]

*Description:*
++++
Se guardan los datos en la Base de datos

_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Base de datos.lvlib:Datos de analisis.vi

*Event type:* Request

:imgpath: Base de datos.lvlib_Datos de analisis.vi.png
image::{imgpath}[Base de datos.lvlib:Datos de analisis.vi]

*Description:*
++++
Recive los datos desde analisis
_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Base de datos.lvlib:Module Did Init.vi

*Event type:* Broadcast

:imgpath: Base de datos.lvlib_Module Did Init.vi.png
image::{imgpath}[Base de datos.lvlib:Module Did Init.vi]

*Description:*
++++
Send the Module Did Init event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Base de datos.lvlib:Status Updated.vi

*Event type:* Broadcast

:imgpath: Base de datos.lvlib_Status Updated.vi.png
image::{imgpath}[Base de datos.lvlib:Status Updated.vi]

*Description:*
++++
Send the Status Updated event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Base de datos.lvlib:Error Reported.vi

*Event type:* Broadcast

:imgpath: Base de datos.lvlib_Error Reported.vi.png
image::{imgpath}[Base de datos.lvlib:Error Reported.vi]

*Description:*
++++
Send the Error Reported event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Base de datos.lvlib:Module Did Stop.vi

*Event type:* Broadcast

:imgpath: Base de datos.lvlib_Module Did Stop.vi.png
image::{imgpath}[Base de datos.lvlib:Module Did Stop.vi]

*Description:*
++++
Send the Module Did Stop event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Base de datos.lvlib:Update Module Execution Status.vi

*Event type:* Broadcast

:imgpath: Base de datos.lvlib_Update Module Execution Status.vi.png
image::{imgpath}[Base de datos.lvlib:Update Module Execution Status.vi]

*Description:*
++++
Broadcast event to specify whether or not the module is running.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

==== Config.lvlib

===== Config.lvlib:Start Module.vi

*Event type:* Not a DQMH Event

:imgpath: Config.lvlib_Start Module.vi.png
image::{imgpath}[Config.lvlib:Start Module.vi]

*Description:*
++++
Launches the Module Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Config.lvlib:Stop Module.vi

*Event type:* Not a DQMH Event

:imgpath: Config.lvlib_Stop Module.vi.png
image::{imgpath}[Config.lvlib:Stop Module.vi]

*Description:*
++++
Send the Stop request to the Module's Main.vi.

If <b>Wait for Module to Stop?</b> is TRUE, this VI will wait until the module main VI stops, and will timeout at the <b>Timeout to Wait for Stop</b> value. This value defaults to "-1", which means the VI will not timeout, and will always wait until the module main VI stops before completing execution.

Note: The <b>Timeout to Wait for Stop</b> value is ignored if 'Wait for Module to Stop?' is set to FALSE.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Config.lvlib:Show Panel.vi

*Event type:* Request

:imgpath: Config.lvlib_Show Panel.vi.png
image::{imgpath}[Config.lvlib:Show Panel.vi]

*Description:*
++++
Send the Show Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Config.lvlib:Hide Panel.vi

*Event type:* Request

:imgpath: Config.lvlib_Hide Panel.vi.png
image::{imgpath}[Config.lvlib:Hide Panel.vi]

*Description:*
++++
Send the Hide Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Config.lvlib:Get Module Execution Status.vi

*Event type:* Request

:imgpath: Config.lvlib_Get Module Execution Status.vi.png
image::{imgpath}[Config.lvlib:Get Module Execution Status.vi]

*Description:*
++++
Fire the Get Module Execution Status request.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Config.lvlib:Show Diagram.vi

*Event type:* Request

:imgpath: Config.lvlib_Show Diagram.vi.png
image::{imgpath}[Config.lvlib:Show Diagram.vi]

*Description:*
++++
This VI tells the Module to show its block diagram to facilitate troubleshooting (add probes, breakpoints, highlight execution, etc).

_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Config.lvlib:Module Did Init.vi

*Event type:* Broadcast

:imgpath: Config.lvlib_Module Did Init.vi.png
image::{imgpath}[Config.lvlib:Module Did Init.vi]

*Description:*
++++
Send the Module Did Init event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Config.lvlib:Status Updated.vi

*Event type:* Broadcast

:imgpath: Config.lvlib_Status Updated.vi.png
image::{imgpath}[Config.lvlib:Status Updated.vi]

*Description:*
++++
Send the Status Updated event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Config.lvlib:Error Reported.vi

*Event type:* Broadcast

:imgpath: Config.lvlib_Error Reported.vi.png
image::{imgpath}[Config.lvlib:Error Reported.vi]

*Description:*
++++
Send the Error Reported event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Config.lvlib:Module Did Stop.vi

*Event type:* Broadcast

:imgpath: Config.lvlib_Module Did Stop.vi.png
image::{imgpath}[Config.lvlib:Module Did Stop.vi]

*Description:*
++++
Send the Module Did Stop event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Config.lvlib:Update Module Execution Status.vi

*Event type:* Broadcast

:imgpath: Config.lvlib_Update Module Execution Status.vi.png
image::{imgpath}[Config.lvlib:Update Module Execution Status.vi]

*Description:*
++++
Broadcast event to specify whether or not the module is running.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

==== Mensajes.lvlib

===== Mensajes.lvlib:Start Module.vi

*Event type:* Not a DQMH Event

:imgpath: Mensajes.lvlib_Start Module.vi.png
image::{imgpath}[Mensajes.lvlib:Start Module.vi]

*Description:*
++++
Launches the Module Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Mensajes.lvlib:Stop Module.vi

*Event type:* Not a DQMH Event

:imgpath: Mensajes.lvlib_Stop Module.vi.png
image::{imgpath}[Mensajes.lvlib:Stop Module.vi]

*Description:*
++++
Send the Stop request to the Module's Main.vi.

If <b>Wait for Module to Stop?</b> is TRUE, this VI will wait until the module main VI stops, and will timeout at the <b>Timeout to Wait for Stop</b> value. This value defaults to "-1", which means the VI will not timeout, and will always wait until the module main VI stops before completing execution.

Note: The <b>Timeout to Wait for Stop</b> value is ignored if 'Wait for Module to Stop?' is set to FALSE.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Mensajes.lvlib:Show Panel.vi

*Event type:* Request

:imgpath: Mensajes.lvlib_Show Panel.vi.png
image::{imgpath}[Mensajes.lvlib:Show Panel.vi]

*Description:*
++++
Send the Show Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Mensajes.lvlib:Hide Panel.vi

*Event type:* Request

:imgpath: Mensajes.lvlib_Hide Panel.vi.png
image::{imgpath}[Mensajes.lvlib:Hide Panel.vi]

*Description:*
++++
Send the Hide Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Mensajes.lvlib:Get Module Execution Status.vi

*Event type:* Request

:imgpath: Mensajes.lvlib_Get Module Execution Status.vi.png
image::{imgpath}[Mensajes.lvlib:Get Module Execution Status.vi]

*Description:*
++++
Fire the Get Module Execution Status request.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Mensajes.lvlib:Show Diagram.vi

*Event type:* Request

:imgpath: Mensajes.lvlib_Show Diagram.vi.png
image::{imgpath}[Mensajes.lvlib:Show Diagram.vi]

*Description:*
++++
This VI tells the Module to show its block diagram to facilitate troubleshooting (add probes, breakpoints, highlight execution, etc).

_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Mensajes.lvlib:Mandar mensajes.vi

*Event type:* Request

:imgpath: Mensajes.lvlib_Mandar mensajes.vi.png
image::{imgpath}[Mensajes.lvlib:Mandar mensajes.vi]

*Description:*
++++
Se manda mensajes a la UI
_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Mensajes.lvlib:Module Did Init.vi

*Event type:* Broadcast

:imgpath: Mensajes.lvlib_Module Did Init.vi.png
image::{imgpath}[Mensajes.lvlib:Module Did Init.vi]

*Description:*
++++
Send the Module Did Init event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Mensajes.lvlib:Status Updated.vi

*Event type:* Broadcast

:imgpath: Mensajes.lvlib_Status Updated.vi.png
image::{imgpath}[Mensajes.lvlib:Status Updated.vi]

*Description:*
++++
Send the Status Updated event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Mensajes.lvlib:Error Reported.vi

*Event type:* Broadcast

:imgpath: Mensajes.lvlib_Error Reported.vi.png
image::{imgpath}[Mensajes.lvlib:Error Reported.vi]

*Description:*
++++
Send the Error Reported event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Mensajes.lvlib:Module Did Stop.vi

*Event type:* Broadcast

:imgpath: Mensajes.lvlib_Module Did Stop.vi.png
image::{imgpath}[Mensajes.lvlib:Module Did Stop.vi]

*Description:*
++++
Send the Module Did Stop event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Mensajes.lvlib:Update Module Execution Status.vi

*Event type:* Broadcast

:imgpath: Mensajes.lvlib_Update Module Execution Status.vi.png
image::{imgpath}[Mensajes.lvlib:Update Module Execution Status.vi]

*Description:*
++++
Broadcast event to specify whether or not the module is running.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

==== UI.lvlib

===== UI.lvlib:Start Module.vi

*Event type:* Not a DQMH Event

:imgpath: UI.lvlib_Start Module.vi.png
image::{imgpath}[UI.lvlib:Start Module.vi]

*Description:*
++++
Launches the Module Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Stop Module.vi

*Event type:* Not a DQMH Event

:imgpath: UI.lvlib_Stop Module.vi.png
image::{imgpath}[UI.lvlib:Stop Module.vi]

*Description:*
++++
Send the Stop request to the Module's Main.vi.

If <b>Wait for Module to Stop?</b> is TRUE, this VI will wait until the module main VI stops, and will timeout at the <b>Timeout to Wait for Stop</b> value. This value defaults to "-1", which means the VI will not timeout, and will always wait until the module main VI stops before completing execution.

Note: The <b>Timeout to Wait for Stop</b> value is ignored if 'Wait for Module to Stop?' is set to FALSE.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Show Panel.vi

*Event type:* Request

:imgpath: UI.lvlib_Show Panel.vi.png
image::{imgpath}[UI.lvlib:Show Panel.vi]

*Description:*
++++
Send the Show Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Hide Panel.vi

*Event type:* Request

:imgpath: UI.lvlib_Hide Panel.vi.png
image::{imgpath}[UI.lvlib:Hide Panel.vi]

*Description:*
++++
Send the Hide Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Get Module Execution Status.vi

*Event type:* Request

:imgpath: UI.lvlib_Get Module Execution Status.vi.png
image::{imgpath}[UI.lvlib:Get Module Execution Status.vi]

*Description:*
++++
Fire the Get Module Execution Status request.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Show Diagram.vi

*Event type:* Request

:imgpath: UI.lvlib_Show Diagram.vi.png
image::{imgpath}[UI.lvlib:Show Diagram.vi]

*Description:*
++++
This VI tells the Module to show its block diagram to facilitate troubleshooting (add probes, breakpoints, highlight execution, etc).

_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Module Did Init.vi

*Event type:* Broadcast

:imgpath: UI.lvlib_Module Did Init.vi.png
image::{imgpath}[UI.lvlib:Module Did Init.vi]

*Description:*
++++
Send the Module Did Init event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Status Updated.vi

*Event type:* Broadcast

:imgpath: UI.lvlib_Status Updated.vi.png
image::{imgpath}[UI.lvlib:Status Updated.vi]

*Description:*
++++
Send the Status Updated event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Error Reported.vi

*Event type:* Broadcast

:imgpath: UI.lvlib_Error Reported.vi.png
image::{imgpath}[UI.lvlib:Error Reported.vi]

*Description:*
++++
Send the Error Reported event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Module Did Stop.vi

*Event type:* Broadcast

:imgpath: UI.lvlib_Module Did Stop.vi.png
image::{imgpath}[UI.lvlib:Module Did Stop.vi]

*Description:*
++++
Send the Module Did Stop event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Update Module Execution Status.vi

*Event type:* Broadcast

:imgpath: UI.lvlib_Update Module Execution Status.vi.png
image::{imgpath}[UI.lvlib:Update Module Execution Status.vi]

*Description:*
++++
Broadcast event to specify whether or not the module is running.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

=== Libraries

This section describes libraries public VIs.

=== Classes

This section describes classes public VIs.

== Legal Information

=== Document creation

This document has been generated using the following tools.

==== Antidoc

Project website: https://wovalab.gitlab.io/open-source/labview-doc-generator/[Antidoc] 

Maintainer website: https://wovalab.com[Wovalab] 

BSD 3-Clause License

Copyright (C) 2019, Wovalab,
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


==== Asciidoc for LabVIEW(TM)

Project website: https://wovalab.gitlab.io/open-source/asciidoc-toolkit/[Asciidoc toolkit] 

Maintainer website: https://wovalab.com[Wovalab] 

BSD 3-Clause License

Copyright (C) 2019, Wovalab,
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


==== Graph Builder

Project website: https://gitlab.com/cgambini/graph-builder[Graph Builder]

BSD 3-Clause License

Copyright (c) 2020, Cyril GAMBINI
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


=== Product used in the project

The documented project has been developed with the following products.

==== DQMH(R)

Copyright (C) 2015-2020 by Delacor, LLC. All Rights Reserved.

Find more details on https://delacor.com/products/dqmh/[Delacor] website

